### ISSUE TITLE
What the Windows version supported?

### ISSUE THREAD

**Issue by JohnDeereLiebhaber** [moritzruth/node-enttec-open-dmx-usb#76]
Is Windows 10 supported mit this code?

Thank you

**Comment by moritzruth** [comment]
As the hardware communication is handled by [serialport](https://serialport.io/) which [supports Windows 10](https://serialport.io/docs/guide-platform-support/#supported-platforms-and-architectures), it should work.

**Comment by djerikkux** [comment]
Thank you I installed everything successfully, but now I have this error from the terminal: SyntaxError: Cannot use import statement outside a module
this is indicated by the terminal. Do you have a solution?

Many greetings

**Comment by JohnDeereLiebhaber** [comment]
thank you i was able to install everything successfully now i just ask one question i use the function device.startsending you have code examples i don't understand how it works (i'm just starting out with programming)

Thanks in advance

**Comment by moritzruth** [comment]
This is the example from README.md:

```js
import { EnttecOpenDMXUSBDevice as DMXDevice } from "enttec-open-dmx-usb";

(async () => {
  const device = new DMXDevice(await DMXDevice.getFirstAvailableDevice())

  device.setChannels({
    1: 0xFF,
    2: 0x44
  })

  // same as
  device.setChannels([0xFF, 0x44])

  // same as
  device.setChannels(Buffer.from([0xFF, 0x44]))
})()
```

If you don't understand it, you should learn the basics of JavaScript, Node.js and DMX first. There are many resources freely available on the internet.
