### ISSUE TITLE
Implementing worker_thread

### ISSUE THREAD

**Issue by ScreamZ** [moritzruth/node-enttec-open-dmx-usb#85]
As this post mention : https://github.com/serialport/node-serialport/issues/1938#issuecomment-1814364985 I think this could be nice to move the core into a worker_thread to avoid blocking, especially with the uSleep function ?

What do you think, i can help on that ?

**Comment by moritzruth** [comment]
Hey, I want to keep this library as simple and low-level as possible. Therefore, I think worker_thread support would be out of scope. For the same reason I don’t want animation support (which is inherently opinionated) in this library.
Feel free though to create a higher-level library with those features included!
